version: '3.7'

services:
  web:
    build:
      context: ./calc_xml
      dockerfile: Dockerfile.prod
    command: gunicorn --timeout 600 calc_xml.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/calc_xml/web/static
      - media_volume:/home/calc_xml/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/calc_xml/web/static
      - media_volume:/home/calc_xml/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:

